# PyInstaller hook for ezdxf  
# Collects necessary data files and hidden imports for ezdxf

from PyInstaller.utils.hooks import collect_data_files, collect_submodules

# Collect ezdxf data files (templates, fonts, patterns, etc.)
datas = collect_data_files('ezdxf')

# Core modules that are imported dynamically
hiddenimports = [
    'ezdxf.entities',
    'ezdxf.entities.dxfns', 
    'ezdxf.entities.dxfgfx',
    'ezdxf.entities.dxfobj',
    'ezdxf.entities.line',
    'ezdxf.entities.circle',
    'ezdxf.entities.arc',
    'ezdxf.entities.lwpolyline',
    'ezdxf.entities.polyline',
    'ezdxf.entities.text',
    'ezdxf.entities.mtext',
    'ezdxf.entities.dimension',
    'ezdxf.entities.hatch',
    'ezdxf.entities.insert',
    'ezdxf.entities.attrib',
    'ezdxf.entities.solid',
    'ezdxf.entities.point',
    'ezdxf.entities.spline',
    'ezdxf.entities.ellipse',
    'ezdxf.entities.viewport',
    'ezdxf.entities.leader',
    'ezdxf.entities.image',
    'ezdxf.entities.mesh',
    'ezdxf.entities.xline',
    'ezdxf.entities.ray',
    'ezdxf.entities.shape',
    'ezdxf.entities.trace',
    'ezdxf.entities.helix',
    'ezdxf.entities.acis',
    'ezdxf.entities.boundary_paths',
    'ezdxf.entities.geodata',
    'ezdxf.layouts',
    'ezdxf.layouts.layouts',
    'ezdxf.layouts.blocklayout',
    'ezdxf.math',
    'ezdxf.math._vector',
    'ezdxf.math._matrix44',
    'ezdxf.math.vector',
    'ezdxf.math.matrix44',
    'ezdxf.math.bbox',
    'ezdxf.math.bulge',
    'ezdxf.math.construct2d',
    'ezdxf.math.transformtools',
    'ezdxf.math.ucs',
    'ezdxf.tools',
    'ezdxf.tools.standards',
    'ezdxf.tools.fonts',
    'ezdxf.tools.pattern',
    'ezdxf.tools.text',
    'ezdxf.tools.handle',
    'ezdxf.sections',
    'ezdxf.sections.header',
    'ezdxf.sections.tables',
    'ezdxf.sections.blocks',
    'ezdxf.sections.classes',
    'ezdxf.sections.objects',
    'ezdxf.sections.entities',
    'ezdxf.query',
    'ezdxf.groupby',
    'ezdxf.units',
    'ezdxf.enums',
    'ezdxf.lldxf',
    'ezdxf.lldxf.tagwriter',
    'ezdxf.lldxf.loader',
    'ezdxf.lldxf.validator',
    'ezdxf.lldxf.tags',
    'ezdxf.lldxf.types',
    'ezdxf.lldxf.repair',
    'ezdxf.lldxf.encoding',
    'ezdxf.lldxf.const',
    'ezdxf.audit',
    'ezdxf.document',
    'ezdxf.filemanagement',
    'ezdxf.proxygraphic',
    'ezdxf.render',
    'ezdxf.render.dim_linear',
    'ezdxf.render.dim_radius',
    'ezdxf.render.dim_diameter',
    'ezdxf.render.dim_curved',
    'ezdxf.render.dim_ordinate',
    'ezdxf.render.hatching',
    'ezdxf.colors',
]

# Exclude addons that need Qt/matplotlib
excludedimports = [
    'ezdxf.addons',
    'ezdxf.addons.browser',
    'ezdxf.addons.drawing',
    'ezdxf.addons.geo', 
    'ezdxf.addons.mtxpl',
    'ezdxf.addons.text2path',
    'ezdxf.addons.r12export',
    'ezdxf.addons.odafc',
    'ezdxf.addons.hpgl2',
    'ezdxf.addons.dwg',
    'ezdxf.addons.dxf2code',
    'ezdxf.addons.importer',
    'ezdxf.addons.meshex',
    'ezdxf.addons.acadctb',
    'ezdxf.addons.iterdxf',
    'ezdxf.addons.openscad',
    'ezdxf.addons.pycsg',
]
